[package]
name = "cvn-package"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cvn-core = { path = "../cvn-core" }
cvn-canonical = { path = "../cvn-canonical" }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "1"

[lib]
path = "src/lib.rs"
